### ISSUE TITLE
Decouple the deletion of the prior node from the deletion of its parent

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/topomath#101]

**Comment by sachingrover211** [comment]
The code has been committed - scenarios tested :
* whenever a user unchecks the dynamic node - prior node is deleted and equations become empty where ever the initial node was part of the equation
* whenever a user checks the dynamic node and node has a value- prior node shows up (this was working before)
* whenever a value is removed and value is set to empty - then prior node should be removed if dynamic is set, code written - testing not complete because of an error handler for the value. Error shown to @riteshsamala on slack. Havent created a card for it yet.

**Comment by sachingrover211** [comment]
@jonwetzel should I create a new pull request for this then? because original pull request has been merged to master.
