### ISSUE TITLE
Alien quantity nodes should not have description field set

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#474]
Test on Desalinization in chapter 3 quiz extra-tca

**Comment by jonwetzel** [comment]
@riteshsamala Can you tell me the steps to test this?  I'm not sure what nodes are being referred to...

**Comment by riteshsamala** [comment]
@jonwetzel there was a case where in alien nodes where the description was being set because of the bug, In desalization problem, when one of the mixture nodes had a wrong slot entry, eventually after the system corrected, these became alien nodes but still had a description before the bug (the description field was turning green).
