### ISSUE TITLE
Print equations when Done 

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#501]
When the user presses Done, and there are no error messages or the user decides to exit from the error messages anyway, then TopoMath displays a popup window that lists the equations of the model, one per line.  This allows the user to copy them into Canvas as their "answer" to the Canvas problem. 

More specifically, for every equation node, print the node's equation, then a CRLF.  Next, for every quantity node, print <variable> = <value> and then a CRLF.  Thus, this text can be pasted into the solver and should be solvable.  Note that units are ignored.

**Comment by jonwetzel** [comment]
@vanlehn Rather than creating a new modal for this and making the user do the copy-paste, I think we can just do the copy directly in javascript.  I suggested that @riteshsamala add a new button to the toolbar which copies the equations to the clipboard.  If that isn't possible, we'll add the button to the modal you proposed, which appears when the user clicks "Done".

**Comment by jonwetzel** [comment]
https://github.com/Dragoon-Lab/topomath/pull/499
