### ISSUE TITLE
Users must enter their ID in order to use the solver

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#502]
When the user clicks on a link to a solver page, they must first enter their ID (a 4 digit number).  The solver looks that up in a table of legal IDs (which we provide prior to the start of the experiment).  If the ID is in the table, then the regular solver screen appears.  If not, then the user is asked to try again.

**Comment by jonwetzel** [comment]
@vanlehn Rather than creating a new modal for this and making the user do the copy-paste, I think we can just do the copy directly in javascript.  I suggested that @riteshsamala add a new button to the toolbar which copies the equations to the clipboard.  If that doesn't work, we'll add the button to the modal you proposed, which appears when the user clicks "Done".

**Comment by jonwetzel** [comment]
Done.
